### ISSUE TITLE
Showing traffic gradient in Trip progress indicator

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android-examples#133]
I am using Drop-In UI to write my navigation application. I have added the trip progress indicator into my infopanel by using this [example](https://docs.mapbox.com/android/navigation/examples/navigation-view-custom-trip-progress/). Is it possible to show a traffic gradient in the trip progress indicator? Could you please demonstrate of showing the gradient?

**Comment by EricGeiler** [comment]
![image](https://user-images.githubusercontent.com/61550186/185455374-67696260-a3f4-4a21-9cd4-1ccad8a7d809.png)
We attempting to achieve a trip progress indicator thats shows a gradient of the traffic connection on the selected route.  

Currently our trip progress indicator looks like this,  very basic white layout, but I'm only really concerned with getting the gradient set properly for the current route selected for nav.

![image](https://user-images.githubusercontent.com/61550186/185455982-e44735fc-1203-4516-889a-0b20df3e0c71.png)

**Comment by abhishek1508** [comment]
We should add a new example with the same code as demonstrated here, but this time the example would show additional code as traffic gradient in the trip progress indicator.

**Comment by cafesilencio** [comment]
I don't think this is possible.  Although the Android progress bar supports multiple colors, as far as I know the proportion of the colors can't be controlled.  For example if the progress bar is configured to show red green and blue, each color would be represented equally.  This doesn't accurately represent traffic.  If the first 15% of the route had moderate traffic, then the next 5% of the route was severe traffic with the rest of the route having low traffic, the colors on the line would need to be represented in those proportions rather than in equal proportions. 

If it's discovered there is a way to configure the Android progress bar with colors represented in different proportions we can point to the code in the SDK that would provide the color proportions based on the route traffic.  At the moment this appears to be a limitation of the Android progress bar.

**Comment by EricGeiler** [comment]
close issue, as it limited currently but the function of the OS.

**Comment by abhishek1508** [comment]
Closing as per comment above.
